language: rust
rust:
  #- stable
  - beta
  - nightly
cache:
  directories:
    - $HOME/.cargo
    - $HOME/.cache
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - export GRPC_VERSION=1.14.2
  - export PROTOBUF_VERSION=3.6.1
  - source ci/install-grpc.sh
  - bash ci/install-protobuf.sh
